### PR TITLE
Extract and export doctest.string

### PR DESCRIPTION
**Pull request by eush77**
It is hard to use a module as a dependency if its interface is built upon the file system.

This PR separates `doctest.string(text, options, callback)` function so that it can be used independently.

```js
> doctest.string('// > 2+2\n// 4')
[ [ true, 4, 4, 2 ] ]
```

### CODE REVIEW

**Comment by davidchambers** [comment]
Are you interested in pursuing this, @eush77?

**Comment by eush77** [comment]
@davidchambers Yeah, I think it's a good thing. I will work on rebasing this branch on top of master.

**Comment by davidchambers** [comment]
Okay. Thanks!

**Comment by eush77** [comment]
Ready for review.

**Comment by davidchambers** [comment]
Thank you for reviving this pull request. In the intervening months the value of the flexibility this change would provide has become apparent to me. That said, I'm not yet convinced that exposing a function for processing bite-sized chunks of JavaScript is quite the right approach. Some time ago, you wrote:

> I was going to build a module on top of `doctest` that would execute doctests in markdown files, specifically examples in READMEs.

I would find such a module very useful. What form do you imagine a compatible README would take? Perhaps something along these lines:

    # asdf

    asdf is a wonderful project because it takes so little effort to type.

    ```javascript
    // > 2 + 2
    // 4
    // > 6 * 7
    // 42
    ```

Given a README in this format what I'd really like to be able to do is write a Unix pipeline:

```console
$ sed '/^[/][/]/!d' README.md | doctest
```

This would strip all the lines not beginning with `'//'`, leaving a valid JavaScript file which could then be piped to `doctest`. Of course, `doctest` would need to be updated to accept standard input – I wonder whether *this* is really the missing feature.

Perhaps you have a different README format in mind. Could you elaborate?

**Comment by eush77** [comment]
Thank you for your interest in this idea. Months have passed since I opened this PR, and now I agree that building readme-based testing tool is not just a matter of applying doctest to strings of JavaScript code.

I do admire the beauty of your sed-based approach, but I don't think that doctest's format is apt for the job. As you demonstrated in your example, using doctest's format would require delimiting all example code in comments, which I think is undesirable for the following reasons:

- No syntax highlighting. Writing all your examples in comments makes it harder for readers to grasp the code and deprives you from a powerful way to emphasize important concepts alongside the code (normally you would just use comments for that).

- Cumbersome to write. Having to write code blocks of comments is not very convenient from a readme writer's point of view since it is just a technical limitation. A friendlier tool could just wrap all code blocks in comments by itself.

- It is not a common format of code examples (I hardly ever seen anything like it before).

Personally, I am very much a fan of the format used by @sindresorhus in his modules - which is kind of the inverse to doctest's.

```js
var camelcaseKeys = require('camelcase-keys');

camelcaseKeys({'foo-bar': true});
//=> {fooBar: true}

var argv = require('minimist')(process.argv.slice(2));
//=> {_: [], 'foo-bar': true}

camelcaseKeys(argv);
//=> {_: [], fooBar: true}
```

It looks superb.

Maybe there is a way to adapt doctest for a format like this with some additional preprocessing, but I am not sure it would be easier than simply reimplementing doctest's functionality on a syntax tree with acorn or esprima.

---

As for this PR, maybe you're right and exposing doctest's functionality this way is not a good idea. And since I have currently no use for this of similar feature anyway, I'm closing this. What do you think?

**Comment by davidchambers** [comment]
I agree with all your points. Thank you for taking the time to share your thoughts, and for doing so in such a clear manner.

As you suggest, doctest needn't be the one and only solution to testing code examples in JavaScript projects. In cases where it's not a good fit we're better off finding (or creating) a more suitable tool. In [Sanctuary][1], for example, I wrote a custom doctest "parser" and tester in a Unix pipeline at the bottom of the project's [makefile][2]:

```bash
	@<index.js \
	    sed -n "/^[ ]*\/\/\. >/{N;p;}" \
	  | sed -e "s:^[ ]*\/\/\. ::" \
	        -e "s:^\([^>].*\):   '\1');:" \
	        -e "s:^> \(.*\):eq(R.toString(\1),:" \
	  | sed "1 s:^:var eq = require('assert').strictEqual, R = require('ramda'), S = require('./');:" \
	  | node
```

It's ugly, certainly, but it works with the beautiful [Transcribe][3]-compatible documentation:

```javascript
  //# head :: [a] -> Maybe a
  //.
  //. Takes a list and returns Just the first element of the list if the
  //. list contains at least one element; Nothing if the list is empty.
  //.
  //. ```javascript
  //. > S.head([1, 2, 3])
  //. Just(1)
  //.
  //. > S.head([])
  //. Nothing()
  //. ```
  S.head = def('head', [Any], at(0));
```

Note that the `//#` and `//.` prefixes do not appear in the output, so the code will receive syntax highlighting when viewed on GitHub.

Once we've resolved #63 I plan to use doctest in place of the somewhat hacky Unix pipeline.


[1]: https://github.com/plaid/sanctuary
[2]: https://github.com/plaid/sanctuary/blob/v0.6.0/Makefile#L40-L46
[3]: https://github.com/plaid/transcribe

**Pull request closed without merging**
